# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - pandoc
      - libxml2-dev
      - libudunits2-dev
      - libgdal-dev
