# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

os:
  - linux
  - osx

# macOS 10.12 version. Hope to fix intermittent Travis Mac failure due to BasicText (https://rb.gy/v6efml)
osx_image: xcode9.2

addons:
  apt:
    packages:
      - pandoc
      - libxml2-dev
      - libudunits2-dev
      - libgdal-dev
